name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup-msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: true
          install: msys2-devel base-devel

      - name: Build
        shell: msys2 {0}
        run: |
          makepkg -Csfri --noconfirm --nocheck

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: '*.pkg.tar.*'
